apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-bonny
  labels:
    app: app-bonny
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-bonny
  template:
    metadata:
      labels:
        app: app-bonny
    spec:
      containers:
        - name: container-bonny
          image: "rg.fr-par.scw.cloud/bonny-registry/bonny-be:49d9782793c111f1de59b99e4d9a04dd0503f42b"
          ports:
          - containerPort: 3000