apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-bonny
  labels:
    app: app-caller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-caller
  template:
    metadata:
      labels:
        app: app-caller
    spec:
      containers:
        - name: container-caller
          image: "rg.fr-par.scw.cloud/bonny-registry/bonny-caller:20251212-150951"
          env:
            - name: BACKEND_URL
              value: "http://app-backend:3000/work"
          ports:
          - containerPort: 3000
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 200m
