apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-caller
  labels:
    app: app-caller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-caller
  template:
    metadata:
      labels:
        app: app-caller
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "3000"
    spec:
      containers:
        - name: container-caller
          image: "rg.fr-par.scw.cloud/bonny-registry/bonny-caller:20251212-154159"
          env:
            - name: BACKEND_URL
              value: "http://bonny-service:3000/work"
            - name: PORT
              value: "3000"
          ports:
          - containerPort: 3000
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 200m
