apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bonny-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: {{.Values.ingressClassName}}
  rules:
    - host: {{.Values.host}}
      http:
        paths:
          - path: /be(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: bonny-service
                port:
                  number: 3000
    - host: {{.Values.host}}
      http:
        paths:
          - path: /caller(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: caller-service
                port:
                  number: 3000
