apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: caller-metrics
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: caller-service
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
  namespaceSelector:
    matchNames:
      - prod-argo-due
