apiVersion: v1
kind: Service
metadata:
  name: caller-service
  labels:
    app: caller-service
spec:
  selector:
    app: app-caller
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000